# Generated by Django 3.2 on 2021-06-12 00:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_auto_20210611_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='day',
            new_name='date',
        ),
    ]
