# Generated by Django 3.2 on 2021-06-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210612_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('process', 'process')], default='process', max_length=150),
        ),
    ]
