# Generated by Django 3.2 on 2021-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_from',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_to',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
