POST http://127.0.0.1:8000/account/registration/
Content-Type: application/json

{
    "user": {
        "email": "test@test.test",
        "username": "foo",
        "first_name": "Петр",
        "last_name": "Петров",
        "password": "Admin1234!"
    }
}

###

POST http://127.0.0.1:8000/account/login/
Content-Type: application/json

{
    "user": {
        "email": "test@test.test",
        "password": "Admin1234!"
    }
}

###
GET http://127.0.0.1:8000/account/user/
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjE5NDY1MDYzfQ.Ym-PKp-9UJRqWJvn5gM1hsaiywUhmpW2UhcyW4zh7YQ

###
POST http://127.0.0.1:8000/account/refresh_token/
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwiZXhwIjoxNjE5NDY1NjE2fQ.CjFUxkQQxEjyygTLvkOVN53OodO6SS6z8e2A9IkzoCQ"
}