# Generated by Django 3.2 on 2021-05-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='created_at'),
        ),
    ]
