# Generated by Django 3.2 on 2021-05-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_lecture_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique_for_date='created_at'),
        ),
    ]
