# Generated by Django 3.2 on 2021-05-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_alter_lecture_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='slug',
        ),
    ]
