# Generated by Django 3.2 on 2021-06-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_remove_lecture_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-created_at']},
        ),
    ]
